/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	/* Set a variable to store the Clock Control Registry Address */
	uint32_t *regClockAddress = (uint32_t *) 0x40023830;

	/* Set a variable to store the mode registry address that corresponds to GPIO B  where the user LED LD2 is connected */
	uint32_t *gpioBModeRegAddress = (uint32_t *) 0x40020400;

	/* Set a variable to store the Port Output registry address for GPIO B where the user LED LD2 is connected */
	uint32_t *gpioBPortOutputRegAddress = (uint32_t *) 0x40020414;

	/* Enable the clock control registry for GPIO B section 6.3.10 in the RM0090 User Manual */
	*regClockAddress |= (1<<1);

	/* Set the GPIO B Mode Register for PB7 where the led LED 2 is connected to output '01' */
	*gpioBModeRegAddress &= ~ (1<<14);
	*gpioBModeRegAddress &= ~ (1<<15);


	/* ***** Here goes the code for the input pin which is PG3 port G pin 3 in this example ***** */

	/* Enable the clock control registry for GPIO g section 6.3.10 in the RM0090 User Manual */
	*regClockAddress |= (1<<6);

	/* Set a variable to store the mode registry address that corresponds to GPIO B  where the user LED LD2 is connected */

	/* ***************************************************
	 * From the section 2.3 Memory map of the RM0090 User Manual of the STM32 MCU GPIO G has the base registry address = 0x4002 1800
	 * From the section 8.4.1 GPIO Port Mode register of the RM0090 User Manual of the STM32 MCU the address offset = 0x00
	 * ***************************************************
	*/
	uint32_t *gpioGModeRegAddress = (uint32_t *) 0x40021800;

	/* ** Set the GPIO B Mode Register for PG3 to input '00'  for that we need to set the bits 6 and 7 ** */
	*gpioGModeRegAddress &= ~(1<<6); // 'x0'
	*gpioGModeRegAddress &= ~(1<<7); // '00'

	*gpioBModeRegAddress |= (1<<14); // '01'

	/* Set a variable to store the Port Input Data register for GPIO G port 3 section 8.4.5 GPIO Port input data register in the RM0090 User Manual */
	/* ****************************************************************************************************************
	 * Section 2.3 Memory Map Base registry address of GPIO G : 0x4002 1800
	 * Section 8.4.5 GPIO Port Input data register address offset : 0x10
	 * *gpioGPortInputRegAddress = 0x4002 1800 + 0x10
	 */
	uint32_t *gpioGPortInputRegAddress = (uint32_t *) 0x40021810;

	 /* Loop forever */
	for(;;)
	{
		/* Read the status of the pin that corresponds to the input  in our case is the 3rd pin of port G*/
		//uint8_t pinStatus = (uint8_t) (*gpioGPortInputRegAddress & (1<<3));
		//or the old school way convert binary mask 1000 to hex 0x8
		uint8_t pinStatus = (uint8_t) (*gpioGPortInputRegAddress & 0x8);

		if(pinStatus)
		{
			//turn on led LD2
			/* Set the GPIO B Port Output Register for PB7 where LED LD2 is connected to 1 (write) section 8.4.6 in the RM0090 User Manual */
			*gpioBPortOutputRegAddress |= (1<<7);
		}
		else
		{
			//turn off led LD2
			/* Set the GPIO B Port Output Register for PB7 where LED LD2 is connected to 0 (read) section 8.4.6 in the RM0090 User Manual */
			*gpioBPortOutputRegAddress &= ~(1<<7);
		}

	}
}
